workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 60

    scripts:
      - name: Navigate to project folder
        script: |
          cd livedub_android

      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew

      - name: Build Debug APK
        script: |
          ./gradlew :app:assembleDebug --stacktrace

    artifacts:
      - livedub_android/app/build/outputs/apk/debug/*.apk
